version: '3'

services:
  nginx:
    image: library/nginx:latest
    container_name: nginx-service
    volumes:
      -  ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx_network
    restart: on-failure

  portainer:
    image: portainer/portainer
    container_name: "portainer-service"
    command: --admin-password '$$2y$$05$$R0vA31aOpCmU8OUUo210FeELJ02ueoQl8Fp6xtKxznQBccZ91nkSu' -H unix:///var/run/docker.sock
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000
    expose:
      - 443
    networks:
      - nginx_network
    restart: always
    
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins-service
    expose:
      - 80
      - 50000
    volumes :
      - jenkins_data:/var/jenkins_home
    networks:
      - nginx_network
    restart: on-failure

  registry:
    image: registry:2
    container_name: registry-service
    restart: always
    ports:
      - 5000:5000
    volumes:
      - registry_data:/var/lib/registry
    networks:
      - nginx_network

  redmine:
    image: redmine:latest
    container_name: redmine-service
    restart: always
    expose:
      - 3000
    volumes:
      - redmine_data:/usr/src/redmine
    environment:
      HTTP_PROXY: http://10.74.66.230:3128
      HTTPS_PROXY: https://10.74.66.230:3128
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
    networks:
      - nginx_network

  db:
    image: mysql:5.7
    container_name: redmine-mysql-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    volumes:
      - redmine_mysql_data:/var/lib/mysql
    networks:
      - nginx_network

  docker:
    image: docker:stable-dind
    container_name: docker-service
    privileged: true
    expose:
      - 2375
    volumes:
      - ${PWD}/docker/daemon.json:/etc/docker/daemon.json
    networks:
      - nginx_network
    restart: on-failure

networks:
  nginx_network:
    driver: bridge
    internal: false
    
volumes:
  jenkins_data:
    driver : local
  portainer_data:
    driver : local
  registry_data:
    driver : local
  redmine_data:
    driver : local
  redmine_mysql_data:
    driver : local
