pipeline {
    agent { node { label 'builder' } }
    stages {
        stage('Compilation and Analysis') {
            parallel {
                stage('Compilation') {
                    steps {
                        git 'https://github.com/LuaDist/libsqlite3.git'
                        sh "./configure && make"
                        recordIssues aggregatingResults: false, enabledForFailure: true, tools: [gcc4(id: 'gcc')]
                    }
                }
                stage('SLOC counting') {
                    agent { node { label 'sloccount' } }
                    steps {
                        git 'https://github.com/LuaDist/libsqlite3.git'
                        sh 'sloccount --duplicates --wide --details . > sloccount.sc'
                        sloccountPublish encoding: '', pattern: 'sloccount.sc'
                    }
                }
                /*
                stage('CPPCheck Analysis') {
                    agent { node { label 'cppcheck' } }
                    steps {
                        git 'https://github.com/LuaDist/libsqlite3.git'
                        sh 'cppcheck --xml --xml-version=2 --enable=all -DPACKAGE_NAME=\"sqlite\" -DPACKAGE_TARNAME=\"sqlite\" -DPACKAGE_VERSION=\"3.7.7.1\" -DPACKAGE_STRING=\"sqlite\\ 3.7.7.1\" -DPACKAGE_BUGREPORT=\"http://www.sqlite.org\" -DPACKAGE_URL=\"\" -DPACKAGE=\"sqlite\" -DVERSION=\"3.7.7.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DHAVE_FDATASYNC=1 -DHAVE_USLEEP=1 -DHAVE_LOCALTIME_R=1 -DHAVE_GMTIME_R=1 -DHAVE_DECL_STRERROR_R=1 -DHAVE_STRERROR_R=1 -DHAVE_POSIX_FALLOCATE=1 -I./src    -D_REENTRANT=1 -DSQLITE_THREADSAFE=1  -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_RTREE sqlite3.c shell.c'
                        recordIssues aggregatingResults: false, enabledForFailure: true, tools: [cppCheck(id: 'cppcheck')]
                    }
                }
                */
            }
        }
    }
}
